server:
  port: 8089

spring:
  application:
    name: wxs
  datasource:
    url: jdbc:mysql://localhost:3306/daigo
    username: wxs
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    content-type: text/html

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl